version: '2.3'
services:
  stylegan:
    image: "eu.gcr.io/stylegan-258409/stylegan:latest"
    build:
      context: .
      dockerfile: ./Dockerfile
    user: "1000:1000"
    runtime: nvidia
    volumes: 
      - './images:/app/images'
      - './results:/app/results'
      - './cache:/app/cache'
      - './checkpoints:/app/checkpoints'
      - './datasets:/app/datasets'

    # command: "python dataset_tool.py create_from_images ./datasets/kanji images/kanji/"
    command: "python train.py"
